### ISSUE TITLE
typo: singular of "dice" is "die"

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-conditional-probability-lab#1]
> A coin is tossed and a single 6-sided dice is rolled. Find the probability of landing on the head side of the coin and rolling a 3 on the dice.

should be 
> A coin is tossed and a single 6-sided die is rolled. Find the probability of landing on the head side of the coin and rolling a 3 on the die.

**Comment by Cheffrey2000** [comment]
The correction to the content has been made and applied to all branches. The issue will be closed out as a result of this commit: https://github.com/learn-co-curriculum/dsc-conditional-probability-lab/commit/6bc74e71e833855adbfad763521c02e124dfa3ad
