### ISSUE TITLE
More detailed solution needed for exercise 6

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-conditional-probability-lab#2]
## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
p_B_given_A = (4/36)/(20/36) 
```

### Concern

This solution doesn't really explain where those numbers came from

## (Optional) Proposed Solution

Write-up from Norman Lo, which can be revised into the appropriate format:
> total possible outcome = 36, total possible outcomes that met the condition either one of the two dices has a value greater than 4 is {[1,5], [1,6], [2,5], [2,6], ....[6,5], [6,6]} = 20, so 20/36 = P(at least 1 dice has greater than 4) = 0.5556  = P(A) in the question. P(B and A) is probability the sum of two dices equal 8 and one of the dices is greater than 4, which the possible outcomes are {[2,6], [3,5], [5,3], [6,2]}, so the P(B and A) is 4/36 = 0.1111, dividing P(B and A) by P(A) should return the conditional probability P(B|A), which is the answer suggested.

**Comment by cwf231** [comment]
Pinging as other students are flagging the same issue.

**Comment by jessepisel** [comment]
Added the proposed explanation above in commit 77b491f3b8103f52bfc187dca9259ef727c5b0ac.

I am closing this issue at this time.
